### ISSUE TITLE
Normalize tenant config permission field names

### ISSUE THREAD

**Issue by loneil** [bcgov/traction#666]
Noticed in the Innkeeper endpoints that fetch the tenant config, the field names for the endorser and public did permissions are different from the endpoints to set those values.

In the following endpoints the fields are named as below
- https://traction-tenant-proxy-dev.apps.silver.devops.gov.bc.ca/api/doc#/traction-innkeeper/put_innkeeper_reservations__reservation_id__config
- https://traction-tenant-proxy-dev.apps.silver.devops.gov.bc.ca/api/doc#/traction-innkeeper/put_innkeeper_tenants__tenant_id__config
- https://traction-tenant-proxy-dev.apps.silver.devops.gov.bc.ca/api/doc#/traction-tenant/get_tenant_config
![image](https://github.com/bcgov/traction/assets/17445138/430fdd80-1f64-4e04-b862-0de28db369b0)

Different from the following endpoints
- https://traction-tenant-proxy-dev.apps.silver.devops.gov.bc.ca/api/doc#/traction-tenant/get_tenant
- [https://traction-tenant-proxy-dev.apps.silver.devops.gov.bc.ca/api/doc#/traction-innkeeper/get_innkeeper_tenants_](https://traction-tenant-proxy-dev.apps.silver.devops.gov.bc.ca/api/doc#/traction-innkeeper/get_innkeeper_tenants_)
- [https://traction-tenant-proxy-dev.apps.silver.devops.gov.bc.ca/api/doc#/traction-innkeeper/get_innkeeper_tenants__tenant_id_](https://traction-tenant-proxy-dev.apps.silver.devops.gov.bc.ca/api/doc#/traction-innkeeper/get_innkeeper_tenants__tenant_id_)
![image](https://github.com/bcgov/traction/assets/17445138/98f1534e-228e-42b6-9e83-33ff648bf734)

AC:
- They all use the first one (past tense makes it seem like they have already connected or registered when it's just a permission to do so in the future)
- Frontend Tenant UI likely needing acapy types [regenerated and updated](https://github.com/bcgov/traction/tree/main/services/tenant-ui/frontend/src/types) and field names changed.

**Comment by esune** [comment]
@loneil is this still something we should look into, or was it resolved with the latest changes pushed by @shaangill025 ?

**Comment by loneil** [comment]
Seems to still have the naming discrepancy.
Priorities I guess, but IMO would be good REST design to have the field names for these be the same everywhere they are used. It's unlikely any LOBs need to make these REST calls though, probably just the Tenant UI so very low impact. But I could see it being confusing for someone starting up a Traction system or anything maybe.

Type of thing you want to get at the beginning rather than ever have to fix it after a bunch of data is in the system or stuff.
